---
title: "git_01"
author: "Tane Sykes"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
How doth the little crocodile  
     Improve his shining tail,   
And pour the waters of the Nile   
     On every golden scale!  
How cheerfully he seems to grin  


## Second Verse
Whose woods these are I think I know.  
His house is in the village though;  
He will not see me stopping here  
To watch his woods fill up with snow.  
My little horse must think it queer  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,   
   Shining with all his might:  
He did his very best to make   
   The billows smooth and bright—  
And this was odd, because it was  
   The middle of the night.  

The moon was shining sulkily,   
   Because she thought the sun  
Had got no business to be there   
   After the day was done—  
“It’s very rude of him," she said,  
   “To come and spoil the fun!”  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Success is counted sweetest   
 By those who ne'er succeed.   
 To comprehend a nectar   
 Requires sorest need.   
Not one of all the purple host   
 Who took the flag to-day   
 Can tell the definition,   
 So clear, of victory!   

As he, defeated, dying,  
 On whose forbidden ear  
 The distant strains of triumph  
 Burst agonized and clear!  